# Generated by Django 3.1.3 on 2020-11-16 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxlover', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='salary',
            name='financial_year_beg',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='salary',
            name='financial_year_end',
            field=models.IntegerField(default=0),
        ),
    ]
