# Generated by Django 3.1.3 on 2020-11-16 11:22

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxlover', '0002_auto_20201116_1719'),
    ]

    operations = [
        migrations.AddField(
            model_name='salary',
            name='basic',
            field=models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=20),
        ),
    ]
