# Generated by Django 3.1.10 on 2021-05-10 02:50

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('taxlover', '0004_auto_20201116_1722'),
    ]

    operations = [
        migrations.CreateModel(
            name='Division',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='taxpayer',
            name='e_tin',
            field=models.CharField(max_length=12, null=True, validators=[django.core.validators.MinLengthValidator(12)]),
        ),
        migrations.AddField(
            model_name='taxpayer',
            name='email',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='taxpayer',
            name='employer_address',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='taxpayer',
            name='employer_bin',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='taxpayer',
            name='employer_name',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='taxpayer',
            name='fathers_name',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='taxpayer',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('T', 'Transgender')], max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='taxpayer',
            name='mobile_no',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='taxpayer',
            name='mothers_name',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='taxpayer',
            name='nid',
            field=models.CharField(max_length=17, null=True),
        ),
        migrations.AddField(
            model_name='taxpayer',
            name='permanent_address',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='taxpayer',
            name='present_address_line_one',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='taxpayer',
            name='present_address_line_two',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='taxpayer',
            name='residence_area',
            field=models.IntegerField(choices=[(1, 'Dhaka and Chittagong City Corporation'), (2, 'Other City Corporation'), (3, 'Other Areas')], null=True),
        ),
        migrations.AddField(
            model_name='taxpayer',
            name='spouse_e_tin',
            field=models.CharField(max_length=12, null=True, validators=[django.core.validators.MinLengthValidator(12)]),
        ),
        migrations.AddField(
            model_name='taxpayer',
            name='spouse_name',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='taxpayer',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='taxpayer',
            name='name',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('division', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='taxlover.division')),
            ],
        ),
        migrations.AddField(
            model_name='taxpayer',
            name='present_address_district',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='taxlover.district'),
        ),
        migrations.AddField(
            model_name='taxpayer',
            name='present_address_division',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='taxlover.division'),
        ),
    ]
