# Generated by Django 3.1.10 on 2021-06-19 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxlover', '0005_auto_20210510_0850'),
    ]

    operations = [
        migrations.AddField(
            model_name='taxpayer',
            name='differently_abled',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='taxpayer',
            name='dob',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='taxpayer',
            name='gazetted_war_wounded_freedom_fighter',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='taxpayer',
            name='government_employee',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='taxpayer',
            name='has_differently_abled_children',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='taxpayer',
            name='married',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='taxpayer',
            name='num_of_dependent_adult',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='taxpayer',
            name='num_of_dependent_child',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='taxpayer',
            name='present_address_postcode',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='taxpayer',
            name='resident',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='taxpayer',
            name='same_address',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='taxpayer',
            name='tax_circle',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='taxpayer',
            name='tax_zone',
            field=models.IntegerField(null=True),
        ),
    ]
