# Generated by Django 3.1.10 on 2021-07-12 00:43

from django.db import migrations, models
import taxlover.models


class Migration(migrations.Migration):

    dependencies = [
        ('taxlover', '0006_auto_20210619_2116'),
    ]

    operations = [
        migrations.AddField(
            model_name='taxpayer',
            name='aged_65_years_or_more',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='taxpayer',
            name='gender',
            field=models.CharField(choices=[(taxlover.models.GenderChoices['M'], 'Male'), (taxlover.models.GenderChoices['F'], 'Female'), (taxlover.models.GenderChoices['T'], 'Transgender')], max_length=1, null=True),
        ),
    ]
