# Generated by Django 3.1.10 on 2021-08-23 05:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('taxlover', '0007_auto_20210712_0643'),
    ]

    operations = [
        migrations.CreateModel(
            name='Income',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salary', models.BooleanField(null=True)),
                ('interest_on_security', models.BooleanField(null=True)),
                ('rental_property', models.BooleanField(null=True)),
                ('agriculture', models.BooleanField(null=True)),
                ('business', models.BooleanField(null=True)),
                ('share_of_profit_in_firm', models.BooleanField(null=True)),
                ('spouse_or_child', models.BooleanField(null=True)),
                ('capital_gains', models.BooleanField(null=True)),
                ('other_sources', models.BooleanField(null=True)),
                ('foreign_income', models.BooleanField(null=True)),
                ('tax_rebate', models.BooleanField(null=True)),
                ('tax_deducted_at_source', models.BooleanField(null=True)),
                ('advance_paid_tax', models.BooleanField(null=True)),
                ('adjustment_of_tax_refund', models.BooleanField(null=True)),
                ('income_year_beg', models.IntegerField(default=0)),
                ('income_year_end', models.IntegerField(default=0)),
                ('tax_payer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='taxlover.taxpayer')),
            ],
        ),
    ]
