# Generated by Django 3.2.6 on 2021-08-26 21:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('taxlover', '0008_income'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('income_year_beg', models.IntegerField(default=0)),
                ('income_year_end', models.IntegerField(default=0)),
                ('document_name', models.CharField(max_length=100, null=True)),
                ('document', models.FileField(upload_to='uploaded_documents')),
                ('description', models.CharField(max_length=250, null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('tax_payer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='taxlover.taxpayer')),
            ],
        ),
    ]
