# Generated by Django 3.2.6 on 2021-08-27 08:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taxlover', '0009_document'),
    ]

    operations = [
        migrations.RenameField(
            model_name='document',
            old_name='document',
            new_name='file',
        ),
    ]
