# Generated by Django 3.2.6 on 2021-09-22 17:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('taxlover', '0012_auto_20210831_0642'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='salary',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='taxlover.salary'),
        ),
    ]
