# Generated by Django 3.2.6 on 2021-09-30 07:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('taxlover', '0013_document_salary'),
    ]

    operations = [
        migrations.CreateModel(
            name='OtherIncome',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('financial_year_beg', models.IntegerField(default=0)),
                ('financial_year_end', models.IntegerField(default=0)),
                ('interest_from_mutual_fund_unit_fund', models.DecimalField(decimal_places=2, max_digits=20, null=True)),
                ('cash_dividend_from_company_listed_in_stock_exchange', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('interest_income_from_wedb', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('conveyance', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('us_dollar_premium_investment_bond', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('pound_sterling_premium_investment_bond', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('euro_premium_investment_bond', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('investment_in_pensioners_savings_instrument', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('sanchaypatra_income', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('others', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('tax_payer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='taxlover.taxpayer')),
            ],
        ),
    ]
