# Generated by Django 3.2.6 on 2021-10-07 09:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('taxlover', '0015_alter_otherincome_interest_from_mutual_fund_unit_fund'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='otherincome',
            name='conveyance',
        ),
        migrations.CreateModel(
            name='TaxRebate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('financial_year_beg', models.IntegerField(default=0)),
                ('financial_year_end', models.IntegerField(default=0)),
                ('life_insurance_premium', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('life_insurance_premium_policy_value', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('contribution_to_pf_as_per_act_1925', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('self_and_employers_contribution_to_pf', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('contribution_to_super_annuation_fund', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('investment_in_approved_debenture_or_stock_or_shares', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('contribution_to_dps', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('contribution_to_benevolent_fund_and_group_insurance_premium', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('contribution_to_zakat_fund', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('investment_in_savings_certificates_sanchaypatra', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('investment_in_bangladesh_govt_treasury_bond', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('donation_to_national_level_institution_set_up_in_the_memory_of_father_of_the_nation', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('donation_to_a_charitable_hospital_recognized_by_nbr', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('donation_to_organizations_set_up_for_the_welfare_of_retarded_people', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('contribution_to_national_level_institution_set_up_in_memory_of_liberation_war', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('contribution_to_liberation_war_museum', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('contribution_to_aga_khan_development_network', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('contribution_to_asiatic_society_bangladesh', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('donation_to_icddrb', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('donation_to_crp', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('donation_to_educational_institution_recognized_by_government', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('contribution_to_ahsania_mission_cancer_hospital', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('mutual_fund', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('tax_payer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='taxlover.taxpayer')),
            ],
        ),
    ]
