# Generated by Django 3.2.6 on 2021-10-16 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxlover', '0018_advancetax'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advancetax',
            name='type',
            field=models.CharField(choices=[('CarAdvanceTax', 'Car Advance Tax'), ('Other', 'Other')], default='Other', max_length=20),
        ),
    ]
