# Generated by Django 3.2.6 on 2021-10-18 00:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('taxlover', '0019_alter_advancetax_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaxRefund',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('financial_year_beg', models.IntegerField(default=0)),
                ('financial_year_end', models.IntegerField(default=0)),
                ('refund', models.DecimalField(decimal_places=2, max_digits=20, null=True)),
                ('tax_payer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='taxlover.taxpayer')),
            ],
        ),
    ]
