# Generated by Django 3.2.6 on 2021-10-19 13:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('taxlover', '0020_taxrefund'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assets',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('income_year_beg', models.IntegerField(default=0)),
                ('income_year_end', models.IntegerField(default=0)),
                ('business_capital', models.BooleanField(null=True)),
                ('directors_shareholding_assets', models.BooleanField(null=True)),
                ('non_agricultural_property', models.BooleanField(null=True)),
                ('agricultural_property', models.BooleanField(null=True)),
                ('investments', models.BooleanField(null=True)),
                ('motor_vehicle', models.BooleanField(null=True)),
                ('furniture', models.BooleanField(null=True)),
                ('jewellery', models.BooleanField(null=True)),
                ('electronic_equipment', models.BooleanField(null=True)),
                ('cash_assets', models.BooleanField(null=True)),
                ('other_assets', models.BooleanField(null=True)),
                ('other_assets_receipt', models.BooleanField(null=True)),
                ('previous_year_net_wealth', models.BooleanField(null=True)),
                ('tax_payer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='taxlover.taxpayer')),
            ],
        ),
    ]
