# Generated by Django 3.2.6 on 2021-10-21 11:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('taxlover', '0024_auto_20211021_0107'),
    ]

    operations = [
        migrations.CreateModel(
            name='MotorVehicle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('financial_year_beg', models.IntegerField(default=0)),
                ('financial_year_end', models.IntegerField(default=0)),
                ('brand_or_type', models.CharField(max_length=100, null=True)),
                ('reg_no', models.CharField(max_length=50, null=True)),
                ('engine_capacity', models.DecimalField(decimal_places=2, max_digits=3, null=True)),
                ('value', models.DecimalField(decimal_places=2, max_digits=20, null=True)),
                ('tax_payer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='taxlover.taxpayer')),
            ],
        ),
    ]
