# Generated by Django 3.2.6 on 2021-10-21 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxlover', '0025_motorvehicle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='motorvehicle',
            name='engine_capacity',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
    ]
