# Generated by Django 3.2.6 on 2021-10-24 08:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taxlover', '0028_rename_description_deductionatsource_deduction_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='advancetax',
            old_name='description',
            new_name='advance_description',
        ),
    ]
