# Generated by Django 3.2.6 on 2021-10-24 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taxlover', '0029_rename_description_advancetax_advance_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='agriculturalproperty',
            old_name='description',
            new_name='property_description',
        ),
        migrations.RenameField(
            model_name='agriculturalproperty',
            old_name='value',
            new_name='property_value',
        ),
    ]
