# Generated by Django 3.2.6 on 2021-10-24 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taxlover', '0030_auto_20211024_1600'),
    ]

    operations = [
        migrations.RenameField(
            model_name='electronicequipment',
            old_name='description',
            new_name='equipment_description',
        ),
        migrations.RenameField(
            model_name='electronicequipment',
            old_name='value',
            new_name='equipment_value',
        ),
        migrations.RenameField(
            model_name='furniture',
            old_name='description',
            new_name='furniture_description',
        ),
        migrations.RenameField(
            model_name='furniture',
            old_name='value',
            new_name='furniture_value',
        ),
        migrations.RenameField(
            model_name='jewellery',
            old_name='description',
            new_name='jewellery_description',
        ),
        migrations.RenameField(
            model_name='jewellery',
            old_name='value',
            new_name='jewellery_value',
        ),
        migrations.RenameField(
            model_name='otherassets',
            old_name='description',
            new_name='asset_description',
        ),
        migrations.RenameField(
            model_name='otherassets',
            old_name='value',
            new_name='asset_value',
        ),
        migrations.RenameField(
            model_name='otherassetsreceipt',
            old_name='description',
            new_name='other_asset_description',
        ),
        migrations.RenameField(
            model_name='otherassetsreceipt',
            old_name='value',
            new_name='other_asset_value',
        ),
        migrations.RenameField(
            model_name='previousyearnetwealth',
            old_name='value',
            new_name='wealth_value',
        ),
    ]
