# Generated by Django 3.2.6 on 2021-11-03 15:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('taxlover', '0031_auto_20211024_2110'),
    ]

    operations = [
        migrations.CreateModel(
            name='Liabilities',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('income_year_beg', models.IntegerField(default=0)),
                ('income_year_end', models.IntegerField(default=0)),
                ('mortgages', models.BooleanField(null=True)),
                ('unsecured_loans', models.BooleanField(null=True)),
                ('bank_loans', models.BooleanField(null=True)),
                ('other_liabilities', models.BooleanField(null=True)),
                ('tax_payer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='taxlover.taxpayer')),
            ],
        ),
    ]
