# Generated by Django 3.2.6 on 2021-11-04 10:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('taxlover', '0033_bankloan_mortgage_otherliability_unsecuredloan'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('financial_year_beg', models.IntegerField(default=0)),
                ('financial_year_end', models.IntegerField(default=0)),
                ('food_expense', models.DecimalField(decimal_places=2, max_digits=20, null=True)),
                ('food_expense_comment', models.CharField(max_length=20, null=True)),
                ('accommodation_expense', models.DecimalField(decimal_places=2, max_digits=20, null=True)),
                ('accommodation_expense_comment', models.CharField(max_length=20, null=True)),
                ('transportation_expense', models.DecimalField(decimal_places=2, max_digits=20, null=True)),
                ('transportation_expense_comment', models.CharField(max_length=20, null=True)),
                ('other_transportation_expense', models.DecimalField(decimal_places=2, max_digits=20, null=True)),
                ('other_transportation_expense_comment', models.CharField(max_length=20, null=True)),
                ('electricity_expense', models.DecimalField(decimal_places=2, max_digits=20, null=True)),
                ('electricity_expense_comment', models.CharField(max_length=20, null=True)),
                ('gas_expense', models.DecimalField(decimal_places=2, max_digits=20, null=True)),
                ('gas_expense_comment', models.CharField(max_length=20, null=True)),
                ('water_expense', models.DecimalField(decimal_places=2, max_digits=20, null=True)),
                ('water_expense_comment', models.CharField(max_length=20, null=True)),
                ('telephone_expense', models.DecimalField(decimal_places=2, max_digits=20, null=True)),
                ('telephone_expense_comment', models.CharField(max_length=20, null=True)),
                ('other_household_expense', models.DecimalField(decimal_places=2, max_digits=20, null=True)),
                ('other_household_expense_comment', models.CharField(max_length=20, null=True)),
                ('children_education_expense', models.DecimalField(decimal_places=2, max_digits=20, null=True)),
                ('children_education_expense_comment', models.CharField(max_length=20, null=True)),
                ('travel_expense', models.DecimalField(decimal_places=2, max_digits=20, null=True)),
                ('travel_expense_comment', models.CharField(max_length=20, null=True)),
                ('festival_expense', models.DecimalField(decimal_places=2, max_digits=20, null=True)),
                ('festival_expense_comment', models.CharField(max_length=20, null=True)),
                ('donation_expense', models.DecimalField(decimal_places=2, max_digits=20, null=True)),
                ('donation_expense_comment', models.CharField(max_length=20, null=True)),
                ('other_special_expense', models.DecimalField(decimal_places=2, max_digits=20, null=True)),
                ('other_special_expense_comment', models.CharField(max_length=20, null=True)),
                ('other_expense', models.DecimalField(decimal_places=2, max_digits=20, null=True)),
                ('other_expense_comment', models.CharField(max_length=20, null=True)),
                ('tax_at_source_expense', models.DecimalField(decimal_places=2, max_digits=20, null=True)),
                ('tax_at_source_expense_comment', models.CharField(max_length=20, null=True)),
                ('last_year_paid_tax_expense', models.DecimalField(decimal_places=2, max_digits=20, null=True)),
                ('last_year_paid_tax_expense_comment', models.CharField(max_length=20, null=True)),
                ('loss_expense', models.DecimalField(decimal_places=2, max_digits=20, null=True)),
                ('loss_expense_comment', models.CharField(max_length=20, null=True)),
                ('gift_expense', models.DecimalField(decimal_places=2, max_digits=20, null=True)),
                ('gift_expense_comment', models.CharField(max_length=20, null=True)),
                ('tax_payer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='taxlover.taxpayer')),
            ],
        ),
    ]
