# Generated by Django 3.2.9 on 2022-11-23 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxlover', '0035_auto_20211104_1759'),
    ]

    operations = [
        migrations.AlterField(
            model_name='motorvehicle',
            name='engine_capacity',
            field=models.DecimalField(decimal_places=2, max_digits=6, null=True),
        ),
    ]
