# Generated by Django 3.2.9 on 2023-11-06 09:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('taxlover', '0036_alter_motorvehicle_engine_capacity'),
    ]

    operations = [
        migrations.CreateModel(
            name='InterestOnSecurities',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('financial_year_beg', models.IntegerField(default=0)),
                ('financial_year_end', models.IntegerField(default=0)),
                ('type', models.CharField(choices=[('Bond', 'Bond'), ('Zero Coupon Bond', 'Zero Coupon Bond'), ('Debenture', 'Debenture'), ('Other Securities', 'Other Securities'), ('Interest from mutual Fund/Unit Fund', 'Interest from mutual Fund/Unit Fund'), ('Cash Dividend from Company Listed in Stock Exchange', 'Cash Dividend from Company Listed in Stock Exchange'), ('Interest on FDR DPS Bank Account', 'Interest on FDR DPS Bank Account')], default='Bond', max_length=100)),
                ('description', models.CharField(blank=True, max_length=250, null=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=20, null=True)),
                ('commission_or_interest', models.DecimalField(decimal_places=2, max_digits=20, null=True)),
                ('tax_payer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='taxlover.taxpayer')),
            ],
        ),
    ]
