# Generated by Django 3.2.9 on 2023-11-06 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxlover', '0037_interestonsecurities'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interestonsecurities',
            name='commission_or_interest',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
        ),
    ]
