from decimal import Decimal

EXTRACT_TABLE_API_KEY = 'hLv5M7b4VWHFRRWpQmoV48ILJVKMohmRqF0dub41'

HOUSE_RENT_MONTHLY_EXEMPTED_RATE = 25000.00
MEDICAL_YEARLY_EXEMPTED_RATE = 120000.00
CONVEYANCE_YEARLY_EXEMPTED_RATE = 30000.00
INTEREST_FROM_MUTUAL_FUND_YEARLY_EXEMPTED_RATE = 25000.00
CASH_DIVIDEND_YEARLY_EXEMPTED_RATE = 50000.00
DPS_MAX_ALLOWED_RATE = 60000.00
INDIVIDUAL_TAX_PAYER_FIRST_SLAB_LIMIT = Decimal(300000)
INDIVIDUAL_TAX_PAYER_FIRST_SLAB_LIMIT_FOR_WOMEN_THIRD_SEX_AND_65_OR_UP_AGED = Decimal(350000)
INDIVIDUAL_TAX_PAYER_SECOND_SLAB_LIMIT = Decimal(100000)
INDIVIDUAL_TAX_PAYER_THIRD_SLAB_LIMIT = Decimal(300000)
INDIVIDUAL_TAX_PAYER_FOURTH_SLAB_LIMIT = Decimal(400000)
INDIVIDUAL_TAX_PAYER_FIFTH_SLAB_LIMIT = Decimal(500000)
INDIVIDUAL_TAX_PAYER_FIRST_SLAB_TAX_RATE = Decimal(0.00)
INDIVIDUAL_TAX_PAYER_SECOND_SLAB_TAX_RATE = Decimal(0.05)
INDIVIDUAL_TAX_PAYER_THIRD_SLAB_TAX_RATE = Decimal(0.10)
INDIVIDUAL_TAX_PAYER_FOURTH_SLAB_TAX_RATE = Decimal(0.15)
INDIVIDUAL_TAX_PAYER_FIFTH_SLAB_TAX_RATE = Decimal(0.20)
INDIVIDUAL_TAX_PAYER_SIXTH_SLAB_TAX_RATE = Decimal(0.25)
INDIVIDUAL_TAX_PAYER_TAX_REBATE_TAXABLE_AMOUNT_SLAB = Decimal(1500000)
INDIVIDUAL_TAX_PAYER_TAX_REBATE_RATE_01 = Decimal(0.15)
INDIVIDUAL_TAX_PAYER_TAX_REBATE_RATE_02 = Decimal(0.10)
INDIVIDUAL_TAX_PAYER_INVESTMENT_MAX_LIMIT = Decimal(15000000)
INDIVIDUAL_TAX_PAYER_INVESTMENT_RATE_ON_TAXABLE_AMOUNT = Decimal(0.25)
INDIVIDUAL_TAX_PAYER_ONE_PAGE_TAXABLE_LIMIT = Decimal(400000)
